(deftheme afternoon
  "Created 2019-02-11.")

(custom-theme-set-variables
 'afternoon
 )

(custom-theme-set-faces
 'afternoon
 '(bold ((((class color) (min-colors 89)) (:weight bold))))
 '(bold-italic ((((class color) (min-colors 89)) (:slant italic :weight bold))))
 '(underline ((((class color) (min-colors 89)) (:underline t))))
 '(italic ((((class color) (min-colors 89)) (:slant italic))))
 '(font-lock-builtin-face ((((class color) (min-colors 89)) (:foreground "LightCoral"))))
 '(font-lock-comment-delimiter-face ((((class color) (min-colors 89)) (:foreground "#969896"))))
 '(font-lock-comment-face ((((class color) (min-colors 89)) (:foreground "#969896"))))
 '(font-lock-constant-face ((((class color) (min-colors 89)) (:foreground "DarkOliveGreen3"))))
 '(font-lock-doc-face ((((class color) (min-colors 89)) (:foreground "moccasin"))))
 '(font-lock-function-name-face ((((class color) (min-colors 89)) (:foreground "goldenrod"))))
 '(font-lock-keyword-face ((((class color) (min-colors 89)) (:foreground "DeepSkyBlue1"))))
 '(font-lock-negation-char-face ((((class color) (min-colors 89)) (:foreground "DeepSkyBlue1"))))
 '(font-lock-preprocessor-face ((((class color) (min-colors 89)) (:foreground "gold"))))
 '(font-lock-regexp-grouping-backslash ((((class color) (min-colors 89)) (:foreground "#e7c547"))))
 '(font-lock-regexp-grouping-construct ((((class color) (min-colors 89)) (:foreground "#c397d8"))))
 '(font-lock-string-face ((((class color) (min-colors 89)) (:foreground "burlywood"))))
 '(font-lock-type-face ((((class color) (min-colors 89)) (:foreground "CadetBlue1"))))
 '(font-lock-variable-name-face ((((class color) (min-colors 89)) (:foreground "#e7c547"))))
 '(font-lock-warning-face ((((class color) (min-colors 89)) (:weight bold :foreground "#d54e53"))))
 '(shadow ((((class color) (min-colors 89)) (:foreground "#969896"))))
 '(success ((((class color) (min-colors 89)) (:foreground "SeaGreen2"))))
 '(error ((((class color) (min-colors 89)) (:foreground "#d54e53"))))
 '(warning ((((class color) (min-colors 89)) (:foreground "goldenrod"))))
 '(match ((((class color) (min-colors 89)) (:foreground "DeepSkyBlue1" :background "#181a26" :inverse-video t))))
 '(isearch ((((class color) (min-colors 89)) (:foreground "#e7c547" :background "#181a26" :inverse-video t))))
 '(isearch-fail ((((class color) (min-colors 89)) (:background "#181a26" :inherit font-lock-warning-face :inverse-video t))))
 '(cursor ((((class color) (min-colors 89)) (:background "goldenrod"))))
 '(fringe ((((class color) (min-colors 89)) (:background "#14151E"))))
 '(linum ((((class color) (min-colors 89)) (:background "#14151E" :foreground "DarkOliveGreen3"))))
 '(border ((((class color) (min-colors 89)) (:background "#14151E"))))
 '(highlight ((((class color) (min-colors 89)) (:inverse-video nil :background "#14151E"))))
 '(mode-line ((((class color) (min-colors 89)) (:foreground nil :background "#14151E" :box (:line-width 1 :color "#eaeaea") :family "Lucida Grande"))))
 '(mode-line-buffer-id ((((class color) (min-colors 89)) (:foreground "#c397d8" :background nil))))
 '(mode-line-inactive ((((class color) (min-colors 89)) (:inherit mode-line :foreground "#969896" :background "#14151E" :weight normal :box (:line-width 1 :color "#eaeaea")))))
 '(mode-line-emphasis ((((class color) (min-colors 89)) (:foreground "#eaeaea" :slant italic))))
 '(mode-line-highlight ((((class color) (min-colors 89)) (:foreground "#c397d8" :box nil))))
 '(minibuffer-prompt ((((class color) (min-colors 89)) (:foreground "DeepSkyBlue1"))))
 '(region ((((class color) (min-colors 89)) (:background "#103050"))))
 '(secondary-selection ((((class color) (min-colors 89)) (:background "#14151E"))))
 '(header-line ((((class color) (min-colors 89)) (:inherit mode-line :foreground "#c397d8" :background nil))))
 '(trailing-whitespace ((((class color) (min-colors 89)) (:foreground "#d54e53" :inverse-video t :underline nil))))
 '(eldoc-highlight-function-argument ((((class color) (min-colors 89)) (:foreground "DarkOliveGreen3" :weight bold))))
 '(link ((((class color) (min-colors 89)) (:foreground nil :underline t))))
 '(widget-button ((((class color) (min-colors 89)) (:underline t))))
 '(widget-field ((((class color) (min-colors 89)) (:background "#14151E" :box (:line-width 1 :color "#eaeaea")))))
 '(custom-variable-tag ((((class color) (min-colors 89)) (:foreground "DeepSkyBlue1"))))
 '(custom-group-tag ((((class color) (min-colors 89)) (:foreground "DeepSkyBlue1"))))
 '(custom-state ((((class color) (min-colors 89)) (:foreground "DarkOliveGreen3"))))
 '(default ((((class color) (min-colors 89)) (:foreground "#eaeaea" :background "#181a26")))))

(provide-theme 'afternoon)
